In [1]:
import torch
from torch import optim

In [8]:
def f(x):
    return torch.cos(x)

In [9]:
x = torch.tensor([0.], requires_grad=True)

x_detached = x.detach().requires_grad_()

In [11]:
ddx, = torch.autograd.grad(f(x_detached).mean(), x_detached, create_graph=True)

In [12]:
ddx

tensor([-0.], grad_fn=<MulBackward0>)

In [13]:
ddx.mean().backward()
# x_detached.grad = d^2/dx^2 f(x, y) = 2
# x.grad unaffected
# y.grad = d/dy d/dx f(x, y) = 2

In [14]:
x_detached.grad

tensor([-1.])

In [16]:
torch.cos(torch.tensor([0.01]))

tensor([0.9999])

In [17]:
def f_new(x):
    return torch.cos(torch.tensor([0])) + ddx * x + x_detached.grad * (x**2)

In [19]:
x_detached.grad * (torch.tensor([0.01])**2)

tensor([-1.0000e-04])

In [22]:
1 - ddx * torch.tensor([0.01]) + x_detached.grad * (torch.tensor([0.01])**2)

tensor([0.9999], grad_fn=<AddBackward0>)

In [18]:
f_new(torch.tensor([0.01]))

RuntimeError: cos_vml_cpu not implemented for 'Long'